// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patches.Infrastructure.Data;

#nullable disable

namespace Patches.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426163633_AddConnectionEntity")]
    partial class AddConnectionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Patches.Domain.Entities.Connection", b =>
                {
                    b.Property<int>("PatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatchId", "InputId", "OutputId");

                    b.HasIndex("InputId");

                    b.HasIndex("OutputId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Patches.Domain.Entities.ConnectionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ConnectionPoints");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HorizontalPitch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatchId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerticalUnits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatchId");

                    b.HasIndex("VendorId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Patch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patch");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Patches.Domain.ValueObjects.ConnectionPointType", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("ConnectionPointType");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Connection", b =>
                {
                    b.HasOne("Patches.Domain.Entities.ConnectionPoint", "Input")
                        .WithMany()
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patches.Domain.Entities.ConnectionPoint", "Output")
                        .WithMany()
                        .HasForeignKey("OutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patches.Domain.Entities.Patch", "Patch")
                        .WithMany("Connections")
                        .HasForeignKey("PatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Input");

                    b.Navigation("Output");

                    b.Navigation("Patch");
                });

            modelBuilder.Entity("Patches.Domain.Entities.ConnectionPoint", b =>
                {
                    b.HasOne("Patches.Domain.Entities.Module", "Module")
                        .WithMany("ConnectionPoints")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Module", b =>
                {
                    b.HasOne("Patches.Domain.Entities.Patch", null)
                        .WithMany("Modules")
                        .HasForeignKey("PatchId");

                    b.HasOne("Patches.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Modules")
                        .HasForeignKey("VendorId");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Module", b =>
                {
                    b.Navigation("ConnectionPoints");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Patch", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Patches.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
